version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          command: |
            wget https://github.com/libgit2/libgit2/releases/download/v1.1.0/libgit2-1.1.0.tar.gz
            tar xzf libgit2-1.1.0.tar.gz
            cd libgit2-1.1.0/
            cmake .
            make
            sudo make install
            pip install --upgrade pip
            pip install -r requirements.txt
            ./run_tests.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
